FROM golang:1.25-alpine

RUN  apk add --no-cache git && go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.19.1 
RUN apk add --no-cache make
RUN go install github.com/air-verse/air@v1.63.8

WORKDIR /app
